# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-25 07:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
